name: ${project.name}
main: ${package.path}.FactionsTopPlugin
version: ${project.version}
description: ${project.description}
author: novucs
softdepend: [EpicSpawners, Essentials, Factions, LegacyFactions, Towny, Vault, MVdWPlaceholderAPI, PlaceholderAPI]

commands:
  ttop:
    aliases: [townytop]
    description: Displays towns and nations in order of worth.
    usage: /<command> [nation] [<page>]

  ttopgui:
    aliases: [townytopgui]
    description: Displays top towns and nations with a GUI.
    usage: /<command> [nation] [<page>]

  ttoprecalculate:
    aliases: [townytoprecalculate, ttoprecalc, ttoprec]
    description: Recalculates all existing towns.
    usage: /<command>

  ttopreload:
    aliases: [townytopreload, ttopr]
    description: Reloads the plugin configuration.
    usage: /<command>

  ttopversion:
    aliases: [townytopversion, ttopv]
    description: Sends the version message.
    usage: /<command>

permissions:
  townytop.user:
    default: true
    children:
      townytop.use: true

  townytop.admin:
    default: op
    children:
      townytop.recalculate: true
      townytop.reload: true
      townytop.sign.break: true
      townytop.sign.create: true
      townytop.user: true

  townytop.*:
    default: false
    children:
      townytop.admin: true

  townytop.use: {default: false}
  townytop.recalculate: {default: false}
  townytop.reload: {default: false}
  townytop.sign.break: {default: false}
  townytop.sign.create: {default: false}